### ISSUE TITLE
Node fs's `existsSync()` Function is Deprecated

### ISSUE THREAD

**Issue by Hunga1** [kethinov/mkroosevelt#25]
This doesn't cause any issues at the moment, but after peeking around the code, I've found that there are calls to this function. [Documentation](https://nodejs.org/api/fs.html#fs_fs_existssync_path) suggests using `fs.statSync()` or `fs.accessSync()`.

**Comment by kethinov** [comment]
Actually @alallier could you submit a PR for this?
